[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = [
    "E",  # pycodestyle error
    "F",  # Pyflakes
    "I",  # isort
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]  # imported but unused

[tool.ruff.lint.isort]
force-single-line = true
single-line-exclusions = ["typing"]
known-first-party = ["keras_rs"]

[tool.mypy]
strict = "True"
exclude = ["_test\\.py$", "^examples"]
disable_error_code = ["import-untyped"]
disallow_subclassing_any = "False"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
addopts = "-vv"
