[tool.black]
line-length = 80

[tool.isort]
profile = "black"
force_single_line = "True"
single_line_exclusions = ["typing"]
known_first_party = ["keras_rs"]
default_section = "THIRDPARTY"
line_length = 80

[tool.mypy]
strict = "True"
exclude = ["_test\\.py$", "^examples"]
disable_error_code = ["import-untyped"]
disallow_subclassing_any = "False"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
addopts = "-vv"
